### ISSUE TITLE
Add constraints to User schema

### ISSUE THREAD

**Issue by chapluck** [somoye/LunchDelivery#28]
Change user.model.js
- [x] Add constraints for length of name, lastName and email fields to be equal or less than 20 characters.
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#data-types

- [x] Add constraints for name, lastName and email fields to not allow null.
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validators-and-allownull-

- [x] Add a constraint for name and lastName fields to allow letters only. Refer to:
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validations

- [x] Add a constraint for email field to allow emails only. Refer to:
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validations

**Comment by bohdan-rebrov** [comment]
All done.
