### ISSUE TITLE
Create user.provider module

### ISSUE THREAD

**Issue by chapluck** [somoye/LunchDelivery#30]
Create _user.provider_ module by analogy with _category.provider_ and _dish.provider_.
- [x] This module should provide methods: _get, getById, add, update, delete_
- [x] Rewrite _user.route_ module to use _user.provider_
- [x] Create _tests/users.test.http_ file by analogy _categories.test.http_ to test user endpoint

**Comment by chapluck** [comment]
precedes #29

**Comment by bohdan-rebrov** [comment]
Create user.provider module #30
Everything done

**Comment by chapluck** [comment]
@paperplane90, please create a pull request
