### ISSUE TITLE
Add a loading panel for all ajax-requests

### ISSUE THREAD

**Issue by chapluck** [somoye/LunchDelivery#5]
The panel should show a "loader"-gif during request and then show a received status  Success or Failure with a reason. The panel should gradually fade out.
Use http://www.w3schools.com/jquery/eff_fadeout.asp
Error statuses map:
400 - Bad request
401 or 403 - Unauthorized
404 - Not Found
500 - Server error
Other statuses: Unknown error
If AJAX request fails with 401 or 403 status code then show login panel if a user is logged in.

If response of failed request contains an object with property 'message' then display it as 'reason' else show 'unknown reason'. An example of response:
{
  "message": "Invalid user email"
}

**Comment by somoye** [comment]
I'm not sure about the following issue: is it ok that user sees "Unauthorized" warning when she/he just opens the page.

**Comment by chapluck** [comment]
If you think it is not ok, then do not show an unauthorized error  message only for initial get user data request
