### ISSUE TITLE
Add increment and decrement for amount of ordered dishes

### ISSUE THREAD

**Issue by somoye** [somoye/LunchDelivery#8]
see 966.com.ua

**Comment by somoye** [comment]
I don't how to make decrement function as I don't how it works on the server side. What should be sent to the server to decrease the number of the dishes.

**Comment by chapluck** [comment]
Send the same request with method DELETE instead of POST

**Comment by chapluck** [comment]
Handle Order, Increment and Decrement operations in the same function instead of three different .

**Comment by chapluck** [comment]
@somoye FYI:
http://stackoverflow.com/questions/5506937/jquery-attrvalue-new-value-not-working
